### PR TITLE
Remove lint and 100 character pernicketiness

### PR DESCRIPTION
**Pull request by rossmuir**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/drive/30)

### CODE REVIEW

**Comment by rossmuir** [comment]
@Fraser - if you could have a look at this one it would be appreciated - no high-five

**Comment by fraser** [comment]
Hi @rossmuir - just noting I think you mentioned the wrong Fraser. :)

**Comment by rossmuir** [comment]
@fraser sorry (again)

**Comment by fraser** [comment]
:+1: no worries!

**Pull request merged**
